"""RawJsonNull

Revision ID: 2d9aa3e9964b
Revises: 
Create Date: 2026-02-10 00:36:05.758317

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d9aa3e9964b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('healthcheck_metrics', sa.Column('content_length', sa.Integer(), nullable=True))
    op.alter_column('pagespeed_metrics', 'raw_json',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('pagespeed_metrics', 'ttfb_ms')
    op.drop_column('pagespeed_metrics', 'latency_ms')
    op.drop_column('pagespeed_metrics', 'inp_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagespeed_metrics', sa.Column('inp_ms', mysql.FLOAT(), nullable=True))
    op.add_column('pagespeed_metrics', sa.Column('latency_ms', mysql.FLOAT(), nullable=True))
    op.add_column('pagespeed_metrics', sa.Column('ttfb_ms', mysql.FLOAT(), nullable=True))
    op.alter_column('pagespeed_metrics', 'raw_json',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('healthcheck_metrics', 'content_length')
    # ### end Alembic commands ###
