"""RawJsonRemoved

Revision ID: 8615bb430e80
Revises: 2d9aa3e9964b
Create Date: 2026-02-18 16:58:03.654432

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8615bb430e80'
down_revision: Union[str, Sequence[str], None] = '2d9aa3e9964b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagespeed_metrics', 'raw_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagespeed_metrics', sa.Column('raw_json', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
